import type { NextPage } from "next";

import Head from "next/head";
import Image from "next/image";
import { Inter, Poppins } from "@next/font/google";

import { useState, Suspense } from "react";

import Navbar from "@components/Navbar/Navbar";
import ServicesCard from "@components/ServicesCard/ServicesCard";
import { CARD_CONTENTS, PROJECTS, CLIENTS, TEAM } from "../app/utils/constants";
import SliderComp from "@components/Slider/SliderComp";
import Clients from "@components/Clients/Clients";

import styles from "../styles/Home.module.css";
import AboutUs from "@components/AboutUs/AboutUs";

const inter = Inter({ subsets: ["latin"] });

const poppins = Poppins({
   subsets: ["latin"],
   weight: ["400", "600"],
});

const Home: NextPage = () => {
   const renderServicesCards = () => {
      return (
         <Suspense fallback={`Loading...`}>
            {CARD_CONTENTS.map(({ imageSrc, title, description }, index) => (
               <ServicesCard
                  key={`${imageSrc}-${index}`}
                  imageSrc={imageSrc}
                  title={title}
                  description={description}
               />
            ))}
         </Suspense>
      );
   };

   return (
      <>
         <Head>
            <title>Brhino Energy Services</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <main className={inter.className}>
            <section className={styles.background_video_container}>
               <video
                  className={styles.background_video}
                  src="./images/bg_video.mp4"
                  autoPlay={true}
                  loop={true}
                  muted={true}
                  playsInline
                  preload="true"
               />
               <Navbar />
               <div className={styles.header}>
                  <h1>
                     BRHINO <br />
                     ENERGY SERVICES
                  </h1>
                  <h3>FOR ALL YOUR NEEDS</h3>
               </div>
               <div className={styles.arrow}>
                  <span></span>
                  <span></span>
                  <span></span>
               </div>
            </section>
            <section className={styles.services_container}>
               <div className={styles.services_wrapper}>
                  <h3>Professional Services</h3>
                  <p>
                     Whether you’re looking for help with something minor or need an experienced professional
                     to take on a larger scale project, I can handle it all. I offer top-notch work at fair
                     and competitive prices. Contact me today for a quote.
                  </p>
                  <div className={styles.services_cards_container}>{renderServicesCards()}</div>
               </div>
            </section>
            <section className={styles.projects_container}>
               <div className={styles.services_wrapper}>
                  <h3>Project Portfolio</h3>
                  <p>
                     Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ad, officia molestias! At
                     laudantium commodi consequuntur, soluta exercitationem possimus, dolorem, vitae odit rem
                     perferendis quidem incidunt sint error? Sint, nobis expedita?
                  </p>
                  <SliderComp content={PROJECTS} />
               </div>
            </section>
            <section className={styles.clients_container}>
               <div className={styles.services_wrapper}>
                  <h3>Our Trusted Clients</h3>
                  <p>
                     Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ad, officia molestias! At
                     laudantium commodi consequuntur, soluta exercitationem possimus, dolorem, vitae odit rem
                     perferendis quidem incidunt sint error? Sint, nobis expedita?
                  </p>
                  <Clients clientData={CLIENTS} />
               </div>
            </section>
            <AboutUs />
            <section className={styles.clients_container}>
               <div className={styles.services_wrapper}>
                  <h3>Meet our Team</h3>
                  <p>
                     Our team is a diverse group of professionals with unique skills and expertise. Together
                     we work towards a common goal and strive for excellence in all we do. Get to know the
                     brilliant minds behind our success, the talented individuals who bring our vision to
                     life, and the passionate people who make up the heart of our organization. Join us as we
                     introduce you to the dedicated individuals who drive our success and make it all
                     possible.
                  </p>
                  <div className={styles.team_container}>
                     {TEAM.map(({ name, designation, imageSrc }, index) => (
                        <div className={styles.team_card} key={`${index}-${imageSrc}`}>
                           <Image
                              src={imageSrc}
                              className={styles.team_image}
                              alt={name}
                              width={100}
                              height={100}
                              priority
                           />
                           <div className={styles.team_contents}>
                              <h3 className={poppins.className}>{name}</h3>
                              <p>{designation}</p>
                           </div>
                        </div>
                     ))}
                  </div>
               </div>
            </section>
         </main>
      </>
   );
};

export default Home;
